import heartIcon from "../assets/images/Fill Heart (1).png";
import eyeIcon from "../assets/images/Fill Eye.png";
import Controller from "../assets/images/controller.png";
import Keyboard from "../assets/images/keyboard.png";
import LCD from "../assets/images/led.png";
import Chair from "../assets/images/chair.png";

import { FaStar } from "react-icons/fa6";

export const cardData = [
  {
    id: 1,
    discount: "-40%",
    heartIcon: heartIcon,
    eyeIcon: eyeIcon,
    image: Controller,
    title: "HAVIT HV-G92 Gamepad",
    newPrice: 120,
    oldPrice: 160,
    ratingStar: FaStar,
  },
  {
    id: 2,
    discount: "-35%",
    heartIcon: heartIcon,
    eyeIcon: eyeIcon,
    image: Keyboard,
    title: "AK-900 Wired Keyboard",
    newPrice: 960,
    oldPrice: 1160,
    ratingStar: FaStar,
  },
  {
    id: 3,
    discount: "-30%",
    heartIcon: heartIcon,
    eyeIcon: eyeIcon,
    image: LCD,
    title: "IPS LCD Gaming Monitor",
    newPrice: 370,
    oldPrice: 400,
    ratingStar: FaStar,
  },
  {
    id: 4,
    discount: "-25%",
    heartIcon: heartIcon,
    eyeIcon: eyeIcon,
    image: Chair,
    title: "S-Series Comfort Chair ",
    newPrice: 375,
    oldPrice: 400,
    ratingStar: FaStar,
  },
  {
    id: 6,
    discount: "-40%",
    heartIcon: heartIcon,
    eyeIcon: eyeIcon,
    image: Controller,
    title: "HAVIT HV-G92 Gamepad",
    newPrice: 120,
    oldPrice: 160,
    ratingStar: FaStar,
  },
  {
    id: 7,
    discount: "-40%",
    heartIcon: heartIcon,
    eyeIcon: eyeIcon,
    image: Controller,
    title: "HAVIT HV-G92 Gamepad",
    newPrice: 120,
    oldPrice: 160,
    ratingStar: FaStar,
  },
  {
    id: 8,
    discount: "-40%",
    heartIcon: heartIcon,
    eyeIcon: eyeIcon,
    image: Controller,
    title: "HAVIT HV-G92 Gamepad",
    newPrice: 120,
    oldPrice: 160,
    ratingStar: FaStar,
  },
  {
    id: 9,
    discount: "-35%",
    heartIcon: heartIcon,
    eyeIcon: eyeIcon,
    image: Keyboard,
    title: "AK-900 Wired Keyboard",
    newPrice: 960,
    oldPrice: 1160,
    ratingStar: FaStar,
  },
  {
    id: 10,
    discount: "-25%",
    heartIcon: heartIcon,
    eyeIcon: eyeIcon,
    image: Chair,
    title: "S-Series Comfort Chair ",
    newPrice: 375,
    oldPrice: 400,
    ratingStar: FaStar,
  },
];
