import Pandu from "../assets/images/pando.png";
import heartIcon from "../assets/images/Fill Heart (1).png";
import eyeIcon from "../assets/images/Fill Eye.png";
import DSLR from "../assets/images/Dslr.png";
import Laptop from "../assets/images/laptop.png";
import MercedesBenz from "../assets/images/mercedes.png";
import SportShoes from "../assets/images/shoes.png";
import Ps4Controller from "../assets/images/pscontroller.png";
import BreakOutJacket from "../assets/images/breakout-jacket.png";
import BeautyProducts from "../assets/images/beautyProducts.png";
import { FaStar } from "react-icons/fa6";

export const ourProductCard = [
  {
    id: 1,
    image: Pandu,
    heartIcon: heartIcon,
    eyeIcon: eyeIcon,
    title: "Breed Dry Dog Food",
    alt: "Breed Dry Dog Food",
    newPrice: 100,
    ratingStar: FaStar,
    radio: false,
    showDiscount: false,
  },
  {
    id: 2,
    image: DSLR,
    heartIcon: heartIcon,
    eyeIcon: eyeIcon,
    title: "CANON EOS DSLR Camera",
    alt: "CANON EOS DSLR Camera",
    newPrice: 360,
    ratingStar: FaStar,
    radio: false,
    showDiscount: false,
  },
  {
    id: 3,
    image: Laptop,
    heartIcon: heartIcon,
    eyeIcon: eyeIcon,
    title: "ASUS FHD Gaming Laptop",
    alt: "ASUS FHD Gaming Laptop",
    newPrice: 700,
    ratingStar: FaStar,
    radio: false,
    showDiscount: false,
  },
  {
    id: 4,
    image: BeautyProducts,
    heartIcon: heartIcon,
    eyeIcon: eyeIcon,
    title: "Curology Product Set ",
    alt: "Curology Product Set",
    newPrice: 500,
    ratingStar: FaStar,
    radio: false,
    showDiscount: false,
  },

  {
    id: 5,
    badge: "New",
    image: MercedesBenz,
    heartIcon: heartIcon,
    eyeIcon: eyeIcon,
    title: "Kids Electric Car",
    alt: "Kids Electric Car",
    newPrice: 960,
    ratingStar: FaStar,
    radio: true,
  },
  {
    id: 6,
    image: SportShoes,
    heartIcon: heartIcon,
    eyeIcon: eyeIcon,
    title: "Jr. Zoom Soccer Cleats",
    alt: "Jr. Zoom Soccer Cleats",
    newPrice: 1160,
    ratingStar: FaStar,
    radio: true,
    showDiscount: false,
  },
  {
    id: 7,
    badge: "New",
    image: Ps4Controller,
    heartIcon: heartIcon,
    eyeIcon: eyeIcon,
    title: "GP11 Shooter USB Gamepad",
    alt: "GP11 Shooter USB Gamepad",
    newPrice: 660,
    ratingStar: FaStar,
    radio: true,
  },
  {
    id: 8,
    image: BreakOutJacket,
    heartIcon: heartIcon,
    eyeIcon: eyeIcon,
    title: "Quilted Satin Jacket",
    alt: "Quilted Satin Jacket",
    newPrice: 660,
    ratingStar: FaStar,
    radio: true,
  },
  {
    id: 9,
    badge: "New",
    image: MercedesBenz,
    heartIcon: heartIcon,
    eyeIcon: eyeIcon,
    title: "Kids Electric Car",
    alt: "Kids Electric Car",
    newPrice: 960,
    ratingStar: FaStar,
    radio: true,
  },
  {
    id: 10,
    image: SportShoes,
    heartIcon: heartIcon,
    eyeIcon: eyeIcon,
    title: "Jr. Zoom Soccer Cleats",
    alt: "Jr. Zoom Soccer Cleats",
    newPrice: 1160,
    ratingStar: FaStar,
    radio: true,
    showDiscount: false,
  },
  {
    id: 11,
    badge: "New",
    image: Ps4Controller,
    heartIcon: heartIcon,
    eyeIcon: eyeIcon,
    title: "GP11 Shooter USB Gamepad",
    alt: "GP11 Shooter USB Gamepad",
    newPrice: 660,
    ratingStar: FaStar,
    radio: true,
  },
  {
    id: 12,
    image: BreakOutJacket,
    heartIcon: heartIcon,
    eyeIcon: eyeIcon,
    title: "Quilted Satin Jacket",
    alt: "Quilted Satin Jacket",
    newPrice: 660,
    ratingStar: FaStar,
    radio: true,
  },
];
